import {
    Wrapper,
    Title,
    Desc,
    ImgWrapper,
    TextWrapper,
    BgImg,
    CustomImage,
    Text
} from './HowItWorksContainer.styled';
import Head from 'next/head';

const HowItWorksContainer = () => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <title> How It Works? | Foody Delivery</title>
            </Head>
            <Wrapper>
                <TextWrapper>
                    <Text>
                        <Title>How it works</Title>
                        <Desc>
                            Delivery may be extended during sale periods. Please refer to the checkout page for an updated estimate for your location. Kindly note that once you have placed an order, it is no longer possible to modify your order. Taxes and duties are included in all product prices.It is possible to place an order with shipment to a different address than your home or billing address when paying with a credit card. Please note that Klarna payments require that your order is shipped to your registered home address.
                        </Desc>
                    </Text>
                </TextWrapper>
                <ImgWrapper>
                    <BgImg />
                    <CustomImage width='600px' height='600px' alt='howitwork' src='/images/howitwork1.svg' />
                </ImgWrapper>
            </Wrapper>

        </>
    );
};

export default HowItWorksContainer;