import Head from 'next/head';
import dynamic from 'next/dynamic';
const Layout = dynamic(() => import('../../components/Layout'));

import { Grid } from '@mui/material';
import { ItemCardWrapper } from './Restaurants.styled'
import ItemCard from './component/ItemCard';
import Paginations from '../../components/paginations';
import RestaurantList from './component/RestaurantList';
import RestaurantListMobile from './component/RestaurantListMobile';

const Restaurant = () => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <title> Restaurant | Foody Delivery</title>
            </Head>
            <Layout>
                <Grid container spacing={2} mt={5}>
                    <Grid item lg={2} md={3} sm={12}>
                        <RestaurantList />
                    </Grid>

                    <Grid item lg={10} md={9} sm={12}>
                        <RestaurantListMobile/>
                        <ItemCardWrapper>
                            <ItemCard />
                            <ItemCard />
                            <ItemCard />
                            <ItemCard />
                            <ItemCard />
                            <ItemCard />
                            <ItemCard />
                            <ItemCard />
                        </ItemCardWrapper>
                        
                        <Paginations />
                    </Grid>
                </Grid>

            </Layout>
        </>
    );
};

export default Restaurant;