import Head from 'next/head';
import { Grid } from '@mui/material';
import { ItemCardWrapper, Containers } from './Restaurants.styled'
import ItemCard from './component/ItemCard';
import Paginations from '../../share/components/paginations';
import RestaurantList from './component/RestaurantList';
import RestaurantListMobile from './component/RestaurantListMobile';
import useSWR from 'swr';
import { useState } from 'react';
import { useCollection } from 'swr-firestore-v9'

const Restaurant = () => {

    const { data } = useCollection('restaurants', {
        orderBy: ['uniqueId', 'asc'],
        listen: true,
    })

    console.log(data)

    const [page, setPage] = useState(1);
    const postsPerPage = Math.ceil(8);
    const last_page = Math.ceil(data && data?.length / postsPerPage)
    const indexOfLastPost = page * postsPerPage;
    const indexOfFirstPost = indexOfLastPost - postsPerPage;
    const currentPosts = data?.slice(indexOfFirstPost, indexOfLastPost)
    const handleChange = (event, value) => {
        setPage(value);
    };


    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <title> Restaurant | Foody Delivery</title>
            </Head>
            <Containers >
                <Grid container mt={5}>
                    <Grid lg={2} md={3} sm={12}>
                        <RestaurantList />
                    </Grid>

                    <Grid lg={10} md={9} sm={12}>
                        <RestaurantListMobile />
                        <ItemCardWrapper>
                            <ItemCard data={currentPosts} />
                        </ItemCardWrapper>
                        <Paginations postsPerPage={last_page} page={page} handleChange={handleChange} />
                    </Grid>
                </Grid>
            </Containers>
        </>
    );
};

export default Restaurant;