import { Wrapper, Wrap, BgCard, Text, Title, Desc } from './AboutUs.styled'
import Head from 'next/head';
import { Grid } from '@mui/material';
import AboutCard from '../../components/aboutCard/AboutCard';

import dynamic from 'next/dynamic';
const Layout = dynamic(() => import('../../components/Layout'))

const AboutUs = () => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <title> About Us | Foody Delivery</title>
            </Head>
            <Layout>
                <Wrapper>
                    <Grid container >
                        <Grid item xs={12} md={12} lg={4}>
                            <Text>
                                <Title>About Us</Title>
                                <Desc>Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.</Desc>
                            </Text>
                        </Grid>
                        <Grid item xs={12} md={12} lg={8}>
                            <Wrap>
                                <BgCard>
                                    <AboutCard top="0" left="0" />
                                    <AboutCard top="310" left="-100" />
                                    <AboutCard top="210" left="200" />
                                    <AboutCard top="550" left="100" />
                                </BgCard>
                            </Wrap>
                        </Grid>
                    </Grid>
                </Wrapper>
            </Layout>
        </>
    );
};

export default AboutUs;